### ISSUE TITLE
Nodejs builder for OpenFunction

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/builder#13]
The [functions-framework-nodejs](https://github.com/OpenFunction/functions-framework-nodejs) project of OpenFunction already supports functions of type OpenFuncAsync, we need to add a new buildpack layer for nodejs in the builder to handle the function framework of nodejs functions.

- [x] Add a new buildpack for the nodejs builder that handles the OpenFuncAsync function
- [x] The new builder can build a nodejs function normally
- [x] Complete docs and samples

**Comment by webup** [comment]
Seems we could mark at least first two tasks as completed? :)

**Comment by benjaminhuo** [comment]
yes, agree!
