### ISSUE TITLE
Optimize the image created by cloud-native buildpacks approach to reduce image size

### ISSUE THREAD

**Issue by lizzzcai** [OpenFunction/builder#31]
**Description**

The current build from the source is not so optimized. I tried to build the hello world program from samples,
1.  [from source](https://github.com/OpenFunction/samples/blob/release-0.5/functions/Knative/hello-world-go/function-sample.yaml)
2. [from dockerfile](https://github.com/OpenFunction/samples/blob/release-0.5/apps/buildah/function-buildah.yaml)

For image built from dockerfile, the image size is about 4MB. For image built from source, the size is about 130MB. Hope that the size of image built from source can be optimized as well.

**Additional context**

Screenshot of the image size for both cases
![image](https://user-images.githubusercontent.com/22748546/149507929-a5cca5a8-bec1-4996-8281-3e634970b320.png)

**Comment by lizzzcai** [comment]
> We're optimizing the image size of the buildpacks approach to use a more light-weighted base run image such as distroless #29, the helloworld sample image could be reduced to 21mb

Thanks @benjaminhuo. that is a great improvement. Not sure if it can be reduced further but I am good with the result for this sample. We can close this ticket.

**Comment by benjaminhuo** [comment]
We'll see if the image size could be reduced further
