### ISSUE TITLE
Link errors

### ISSUE THREAD

**Issue by penghuima** [OpenFunction/builder#5]
When I click on links such as Go1.16, it returns error report 404
![image](https://user-images.githubusercontent.com/43670120/124441771-9cd22d80-ddae-11eb-88d6-4fca432157b7.png)
![image](https://user-images.githubusercontent.com/43670120/124441799-a78cc280-ddae-11eb-97fc-a37704b56ba2.png)

**Comment by tpiperatgod** [comment]
It looks like it's fixed now, close the issue
