### ISSUE TITLE
plugin name bug

### ISSUE THREAD

**Issue by wentevill** [OpenFunction/builder#51]
# Actual Behavior
See https://github.com/OpenFunction/builder/blob/main/cmd/go/of_functions_framework/main.go#L318-L318
```go
if plg.IsDir() && strings.HasPrefix(plg.Name(), "plugin-") 
```
https://github.com/OpenFunction/builder/blob/main/cmd/go/of_functions_framework/main.go#L329-L329
Since the above condition exists, this condition is always True.
```go
if strings.Contains(plg.Name(), "-")
```

**Comment by benjaminhuo** [comment]
@tpiperatgod We cannot use `-` to split the plugins?
https://github.com/OpenFunction/builder/blob/main/cmd/go/of_functions_framework/main.go#L330

**Comment by wentevill** [comment]
Is it possible to output errors to the log, and kill the entire process? instead of ignoring it.
```go

plgFiles, err := ioutil.ReadDir(plgAbsPath)
if err != nil {
   continue
}
```
https://github.com/OpenFunction/builder/blob/main/cmd/go/of_functions_framework/main.go#L320-L323

**Comment by tpiperatgod** [comment]
This is indeed a bug, and the second `if` statement needs to be removed.

> @tpiperatgod We cannot use `-` to split the plugins? https://github.com/OpenFunction/builder/blob/main/cmd/go/of_functions_framework/main.go#L330

Here we can skip the `if` statement and split the plugin's name directly.



> Is it possible to output errors to the log, and kill the entire process? instead of ignoring it.
> 
> ```go
> plgFiles, err := ioutil.ReadDir(plgAbsPath)
> if err != nil {
>    continue
> }
> ```
> 
> https://github.com/OpenFunction/builder/blob/main/cmd/go/of_functions_framework/main.go#L320-L323

I don't think it's necessary to abort for failing to look up the plugin, but a log should be added...

**Comment by benjaminhuo** [comment]
We need to recreate openfunction/builder-go:v2-1.16 ?

**Comment by tpiperatgod** [comment]
Yes, I will update the default functions-framework-go version to v0.2.3 at the same time
